language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer validate
  - composer self-update

install:
  - composer update

script:
  - ./vendor/bin/phpunit;

jobs:
  fast_finish: true
  include:
  - stage: Test
    name: Lowest dependencies
    php: 7.4
    install: composer update --prefer-dist --prefer-lowest

  - stage: Code Quality
    name: Code coverage
    php: 7.4
    before_script:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
    - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
    script:
    - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
    after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

  - stage: Code Quality
    name: Static analysis
    php: 7.4
    script:
      - ./vendor/bin/phpstan analyse -c phpstan.neon --no-progress --no-interaction;
      - ./vendor/bin/psalm --show-info=false
      - ./vendor/bin/phpmetrics --exclude=Exception src

  - stage: Code Quality
    name: Coding standards
    php: 7.4
    script:
      - ./vendor/bin/phpcs
